on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.local/share/racket
          key: ${{ runner.os }}-raco-${{ hashFiles('**/info.rkt') }}
      - uses: Bogdanp/setup-racket@v0.6
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'regular'
          version: '8.1'
      - run: raco pkg install --auto --no-setup --skip-installed
      - run: raco setup --fast-clean contract-etc
      - run: raco setup contract-etc
      - run: raco test --drdr .
